### PR TITLE
`timestamp` and `date` logical fields test

### PR DESCRIPTION
**Pull request by raulraja**
Supporting tests for `logicalTypes` in avrohugger.

```
@namespace("test")

protocol LogicalIDL {

  record LogicalIdl {
    // scala.math.BigDecimal
    decimal(20, 8) dec = 8888.88;
    // java.time.LocalDateTime
    timestamp_ms ts = 1526573732000; //ms from the unix epoch
    // java.time.LocalDate
    date dt = 600; //days from the unix epock, no time precission
  }

}
```

### CODE REVIEW

**Comment by fedefernandez** [comment]
We had to add the `ToSchema`, `ToValue` and `FromValue` instances in freestyle-rpc for serializing BigDecimal inside case classes
https://github.com/frees-io/freestyle-rpc/blob/4d9925959caf9b9f27c7365d087f8116db266125/modules/internal/src/main/scala/encoders.scala#L87-L99

**Comment by raulraja** [comment]
@fedefernandez were you seeing also?
```
org.apache.avro.AvroRuntimeException: Unknown datum class: class scala.math.BigDecimal (JacksonUtils.java:87)
```

**Comment by fedefernandez** [comment]
no, that error is new for me (first time I see `datum` or an error coming from "Jackson" stuff). But because the error was inside a macro expansion, maybe it was hidden. Anyway, that error looks to me like an error trying to serialize the value as JSON.

**Comment by raulraja** [comment]
The instances seem to not be necessary if you add the implicits for the default scala and precision but I'm still seeing the same error even if I add the implicits that Freestyle adds. It's a runtime error so in both cases was finding the implicit evidences just fine.

**Comment by JesusMtnez** [comment]
I've just discovered the problem is related when the BigDecimal is used in a `union`.

**Comment by raulraja** [comment]
@JesusMtnez @fedefernandez  thanks, that's right, we actually discussed the same thing @julianpeeters and I when this same thing happen in #50 . I think Julian and I realized that unions can only contain logical and primitive types if wrapped into records such as the Coproduct is of the records and not a bunch of primitive values. We've seen that avro4s correctly produces encoders and decoders but once the bytes get to the underlying avro serializers they bail with the exception. //cc @sksamuel

**Comment by JesusMtnez** [comment]
@raulraja as far as I could test, `unions` could contain primitive and logical types. The problem happens when the `union` with a `BigDecima` has a default value assign. But if there is no default value, no problem at all.

I'm currently working on this branch trying to solve the problem: https://github.com/47deg/avro4s/tree/fix/bigdecimal-inside-option

**Comment by sksamuel** [comment]
I've merged the PR so many thanks for that.

I've been looking at this problem today myself and there two issues. One is what you've just fixed. The other is that when you use nested classes, the way avro4s generates the default value doesn't work. In [this line](https://github.com/sksamuel/avro4s/blob/master/avro4s-macros/src/main/scala/com/sksamuel/avro4s/SchemaFor.scala#L365), the $member field should be qualified to the nested scope.

**Comment by sksamuel** [comment]
I've released 1.9.0 of avro4s which should address the points mentioned here thanks to @JesusMtnez  PR and my change to default value. @raulraja  @fedefernandez

**Comment by raulraja** [comment]
thanks @sksamuel @JesusMtnez . I updated the tests build to avro4s 1.9.0 and it seems to work just fine with the union cases as well. :tada:

**Comment by JesusMtnez** [comment]
Thank you @sksamuel !! :blush:

**Comment by sksamuel** [comment]
You're welcome. 

Question - this project seems to the same as https://github.com/sksamuel/sbt-avro4s. If so, the community does not need two projects. I'm happy to discontinue sbt-avro4s or whatever if this project is more feature rich, and just concentrate on avro4s for schema generation.

**Comment by sksamuel** [comment]
I don't generate case classes from avro schemas myself, so I don't know myself if there's anything that sbt-avro4s does that sbt-avrohugger doesn't? If the answer is _nothing_, then there's no point me keeping that project active, and I will point people to this project from that homepage.

Thoughts @raulraja @fedefernandez  @JesusMtnez  @julianpeeters

**Comment by julianpeeters** [comment]
@sksamuel @raulraja @fedefernandez @JesusMtnez ~I'm not biased against duplicate libs, but I think the answer is in fact _nothing_, so from my perspective I'd vote to do as you suggest.~ Ah, avrohugger doesn't yet generate `fixed` so I'll aim to remedy that.

**Pull request merged**
