### PR TITLE
Add support for referring dependent array types

### PR DESCRIPTION
**Pull request by skate056**
Detects dependent array types (as per the [Avro spec](https://avro.apache.org/docs/1.7.7/spec.html#Arrays)) so that the different schema files are compiled in the correct order.

```javascript
{
  "type": "array", 
  "items": "string"
}
```

### CODE REVIEW

**Comment by julianpeeters** [comment]
Wonderful, thanks for cleaning up/adding referred types! One last thing though, it looks like one of the `sbt scripted` tests is failing (GenerateSpecificScalaAndJava) because it has an enum that has no "items" key. 

Thanks for all your efforts,
Julian

**Comment by skate056** [comment]
Oh. Didn't realise there was a failing test. Let me have a look. Is there a
special was to run tests in addition to "sbt clean test"?

**Comment by julianpeeters** [comment]
Yes, `sbt scripted` will use the [scripted plugin] (http://eed3si9n.com/testing-sbt-plugins) to run some integration tests (prjoects) that live in sbt-avrohugger/src/sbt-test.

**Comment by skate056** [comment]
Hello Julian,

I did run `sbt scripted` but it runs successfully. Are you running a
different command? Can you send me the error you are getting?

Running projects / GenerateSpecificFromAVSC
Running projects / GenerateScavroFromAVDL
Running projects / GenerateScavroFromAVSC
Running projects / GenerateScavroFromAVRO
Running projects / GenerateWithImports
Running projects / GenerateScalaFromAVSC
Running projects / GenerateSpecificFromAVDL
Running projects / OverrideSettings
Running projects / GenerateSpecificScalaAndJava
Running projects / GenerateScalaFromAVDL
Running projects / GenerateScalaFromAVRO
[success] Total time: 202 s, completed 13-Jan-2016 14:21:37
sbt-avrohugger (master) $

**Comment by julianpeeters** [comment]
Hmm, looks like the issue arrises after upgrading the avrohugger dependency from 0.8.1 to 0.8.2: 

```[info] [info] Resolving org.scala-lang#scala-library;2.10.5 ...
       [info] Resolving org.scala-lang#scala-compiler;2.10.5 ...
       [info] Resolving org.scala-lang#scala-reflect;2.10.5 ...
       [info] Resolving org.scala-lang#jline;2.10.5 ...
       [info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] [info] Done updating.
[info] [success] Total time: 0 s, completed Jan 13, 2016 11:21:18 AM
[info] java.util.NoSuchElementException: key not found: items
[info] 	at scala.collection.MapLike$class.default(MapLike.scala:228)
[info] 	at scala.collection.AbstractMap.default(Map.scala:58)
[info] 	at scala.collection.MapLike$class.apply(MapLike.scala:141)
[info] 	at scala.collection.AbstractMap.apply(Map.scala:58)
[info] 	at sbtavrohugger.AVSCFileSorter$$anonfun$3$$anonfun$apply$3.apply(AVSCFileSorter.scala:88)
[info] 	at sbtavrohugger.AVSCFileSorter$$anonfun$3$$anonfun$apply$3.apply(AVSCFileSorter.scala:67)
[info] 	at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:722)
[info] 	at scala.collection.immutable.Map$Map2.foreach(Map.scala:130)
[info] 	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:721)
[info] 	at sbtavrohugger.AVSCFileSorter$$anonfun$3.apply(AVSCFileSorter.scala:67)
[info] 	at sbtavrohugger.AVSCFileSorter$$anonfun$3.apply(AVSCFileSorter.scala:66)
[info] 	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
[info] 	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
[info] 	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
[info] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
[info] 	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
[info] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[info] 	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
[info] 	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
[info] 	at sbtavrohugger.AVSCFileSorter$.findReferredTypes(AVSCFileSorter.scala:66)
[info] 	at sbtavrohugger.AVSCFileSorter$.strContainsType(AVSCFileSorter.scala:40)
[info] 	at sbtavrohugger.AVSCFileSorter$$anonfun$5$$anonfun$apply$4.apply(AVSCFileSorter.scala:100)
[info] 	at sbtavrohugger.AVSCFileSorter$$anonfun$5$$anonfun$apply$4.apply(AVSCFileSorter.scala:98)
[info] 	at scala.collection.TraversableOnce$$anonfun$count$1.apply(TraversableOnce.scala:114)
[info] 	at scala.collection.TraversableOnce$$anonfun$count$1.apply(TraversableOnce.scala:113)
[info] 	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
[info] 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
[info] 	at scala.collection.TraversableOnce$class.count(TraversableOnce.scala:113)
[info] 	at scala.collection.AbstractTraversable.count(Traversable.scala:105)
[info] 	at sbtavrohugger.AVSCFileSorter$$anonfun$5.apply(AVSCFileSorter.scala:98)
[info] 	at sbtavrohugger.AVSCFileSorter$$anonfun$5.apply(AVSCFileSorter.scala:96)
[info] 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
[info] 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
[info] 	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
[info] 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
[info] 	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
[info] 	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
[info] 	at sbtavrohugger.AVSCFileSorter$.usedUnusedSchemas(AVSCFileSorter.scala:96)
[info] 	at sbtavrohugger.AVSCFileSorter$.sortSchemaFiles(AVSCFileSorter.scala:28)
[info] 	at sbtavrohugger.FileWriter$.generateCaseClasses(FileWriter.scala:22)
[info] 	at sbtavrohugger.formats.specific.SpecificGeneratorTask$$anonfun$specificCaseClassGeneratorTask$1$$anonfun$1.apply(SpecificGeneratorTask.scala:36)
[info] 	at sbtavrohugger.formats.specific.SpecificGeneratorTask$$anonfun$specificCaseClassGeneratorTask$1$$anonfun$1.apply(SpecificGeneratorTask.scala:34)
[info] 	at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:235)
[info] 	at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:235)
[info] 	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:249)
[info] 	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:245)
[info] 	at sbt.Difference.apply(Tracked.scala:224)
[info] 	at sbt.Difference.apply(Tracked.scala:206)
[info] 	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:245)
[info] 	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:244)
[info] 	at sbt.Difference.apply(Tracked.scala:224)
[info] 	at sbt.Difference.apply(Tracked.scala:200)
[info] 	at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:244)
[info] 	at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:242)
[info] 	at sbtavrohugger.formats.specific.SpecificGeneratorTask$$anonfun$specificCaseClassGeneratorTask$1.apply(SpecificGeneratorTask.scala:38)
[info] 	at sbtavrohugger.formats.specific.SpecificGeneratorTask$$anonfun$specificCaseClassGeneratorTask$1.apply(SpecificGeneratorTask.scala:31)
[info] 	at scala.Function6$$anonfun$tupled$1.apply(Function6.scala:35)
[info] 	at scala.Function6$$anonfun$tupled$1.apply(Function6.scala:34)
[info] 	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
[info] 	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
[info] 	at sbt.std.Transform$$anon$4.work(System.scala:63)
[info] 	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
[info] 	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
[info] 	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[info] 	at sbt.Execute.work(Execute.scala:235)
[info] 	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
[info] 	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
[info] 	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
[info] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
[info] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[info] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[info] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[info] 	at java.lang.Thread.run(Thread.java:745)
[info] [error] (avro:generateSpecific) java.util.NoSuchElementException: key not found: items
[info] [error] Total time: 0 s, completed Jan 13, 2016 11:21:19 AM
[error] x projects / GenerateSpecificScalaAndJava
[error]    {line 3}  Command failed: avro:generate-specific failed```

For avrohugger 0.8.2, some tests were restructured, but the only changes to the runtime were an update to the list datatype. It seems unlikely that the "items" key in this error is from that work, simply because 0.8.2 works fine in sbt-avrohugger prior to your PR. But, off the top of my head, that leaves me a little stumped as to the cause. If you're eager to get this merged, I can help take a deeper look.

**Comment by julianpeeters** [comment]
Oh, now I see why it was passing for us. We had made changes without bumping the version, so "scripted" was picking up the old version of sbt-avrohugger from maven-central instead of the new version publish to the local ivy repo.

If I bump sbt-avrohugger to 0.7.2-SNAPSHOT, then that scripted tests fails as expected.

So it looks like just that enum case remains.

**Comment by skate056** [comment]
Have fixed the tests and merged from master. @julianpeeters Can you please give this a try again? Do you want me to bump up the minor version?

**Comment by julianpeeters** [comment]
Looks great. Thanks for contributing. Version 0.9.0 should be syncing with maven central shortly.

**Pull request merged**
