### PR TITLE
Update some missing dependencies

### PR DESCRIPTION
**Pull request by fedefernandez**

### CODE REVIEW

**Comment by fedefernandez** [comment]
@julianpeeters do you know if this could fix the problems you're getting in #73, can we give it a try? Thanks

**Comment by julianpeeters** [comment]
@fedefernandez seems promising, much thanks. However I'm running into errors trying to upgrade avro4s, which was being used here to generate a `GenericRecord` to be serialied with java avro, for example, in `GenericDecimalTaggedSerializationTests`:
```
[info] [error] /tmp/sbt_2d670c2d/GenericDecimalTaggedSerializationTests/src/test/scala/test/DecimalsTaggedSpec.scala:35:37: could not find implicit value for parameter schemaFor: com.sksamu
el.avro4s.SchemaFor[example.idl.LogicalOptionalIdl]
[info] [error]   implicit val schemaFor = SchemaFor[LogicalOptionalIdl]
[info] [error]                                     ^
[info] [error] /tmp/sbt_2d670c2d/GenericDecimalTaggedSerializationTests/src/test/scala/test/DecimalsTaggedSpec.scala:209:32: could not find implicit value for evidence parameter of type com

.sksamuel.avro4s.Encoder[example.idl.LogicalOptionalIdl]
[info] [error]       val format = RecordFormat[LogicalOptionalIdl]
```
I didn't get very far in finding a solution yet, but the avro4s here is just for convenience, and the generated classes seem small enough where the GenericRecords could be made by hand. I'll likely take another shot this weekend

**Comment by fedefernandez** [comment]
@julianpeeters I see, well no worries then. It's not a blocker for us right now.

**Comment by julianpeeters** [comment]
I took another swing and completed the avro4s upgrade, however I'm experiencing the same error about decimal default values not being recognized as a decimal.

I also noticed that an untagged BigDecimal gives another error: 
```
[error]   x deserialize correctly
[error]    '{"data": "\u0005´"}'
[error]
[error]     is not equal to
[error]
[error]    'ImmutableRecord({"type":"record","name":"LogicalSc","namespace":"test.DecimalsSpec","fields":[{"name":"data","type":{"type":"bytes","logicalType":"decimal","precision":8,"
scale":2},"default":"9999.99"}]},Vector(java.nio.HeapByteBuffer[pos=0 lim=2 cap=2]))' (StandardTestUtil.scala:43)
[error] Actual:   {"data": "\u0005´"}
[error] Expected: ImmutableRecord({"type":"record","name":"LogicalSc","namespace":"test.DecimalsSpec","fields":[{"name":"data","type":{"type":"bytes","logicalType":"decimal","precisio
n":8,"scale":2},"default":"9999.99"}]},Vector(java.nio.HeapByteBuffer[pos=0 lim=2 cap=2]))
```

**Comment by julianpeeters** [comment]
available in 2.0.0-RC20

**Pull request closed without merging**
