### PR TITLE
Avdl file order

### PR DESCRIPTION
**Pull request by jon-morra-zefr**
This is a working example of correctly ordering AVDL files for compilation.  I have a test that shows this works under some pretty adverse conditions.  Namely the case when we have a AVDL file named `a.avdl` and then a directory called `foo` with another file called `a.avdl`.  Since it works under those conditions I feel pretty confident.  This change also works for my specific problem in #34.

The only part I don't like about this is the regex to find the imports, this seems brittle.  Ideally I'd like to actually use avro to parse the file and get the imports that way, but I couldn't figure out how to do it.

### CODE REVIEW

**Comment by jon-morra-zefr** [comment]
@julianpeeters I think at this point I'm done updating this PR.  I've made the code as conscience and performant as I can by making use of tail recursion and not intermediate data structures.  Let me know if you need more information before this is merged in.

**Comment by jon-morra-zefr** [comment]
I think I just found a bug, fixing now.

**Comment by jon-morra-zefr** [comment]
@julianpeeters sorry for the increase in messages, the bug I thought I found was actually within one of our projects.  This is good to go.

**Comment by julianpeeters** [comment]
@jon-morra-zefr very nice. Let's throw those 3 test avdls in the example project in the [sbt-test](https://github.com/julianpeeters/sbt-avrohugger/tree/master/src/sbt-test/sbt-avrohugger/basic) directory as a simple integration test. Have you used `sbt scripted` before for testing plugins? The "expectation" goes in the [test](https://github.com/julianpeeters/sbt-avrohugger/blob/master/src/sbt-test/sbt-avrohugger/basic/test) file.

(If you were wondering, the avsc tests are duped (A and _A) because avsc sorting requires digging for schema/record names instead of file names, and they can be fully- or un-qualified, and need )

**Comment by julianpeeters** [comment]
* in addition to the existing unit tests in scala/test.

**Comment by jon-morra-zefr** [comment]
@julianpeeters, I've added new tests to sbt-test.  I've never worked within an SBT plugin before so this is good for me to know.  Everything passes when running sbt scripted.  Please let me know if you need more work done.

**Pull request merged**
